# -*- coding: utf-8 -*-
"""CSC767_FinalProject_Part2_adagrad.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wJGMPLssKRQK3bzmUlb0Zmemwjrj71a8
"""

!git clone https://github.com/rwightman/pytorch-image-models

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/pytorch-image-models/

!python train.py 1   --model resnet50d --sched cosine --epochs 40 --warmup-epochs 5 --lr 5e-3 --bce-target-thresh 0.2  --smoothing 0.1 --mixup 0.2 --batch-size 32 --amp -j 2 --opt adagrad

!python validate.py /content/drive/MyDrive/imagenette2-320/val/ --model resnet50d --checkpoint ./output/train/20220512-160456-resnet50d-224/checkpoint-43.pth.tar

!python inference.py /content/drive/MyDrive/imagenette2-320/val/ --model resnet50d --checkpoint ./output/train/20220512-160456-resnet50d-224/checkpoint-43.pth.tar

!python validate.py /content/drive/MyDrive/imagenette2-320/val/ --model resnet50d --checkpoint ./output/train/20220512-160456-resnet50d-224/checkpoint-49.pth.tar

!python validate.py /content/drive/MyDrive/imagenette2-320/val/ --model resnet50d --checkpoint ./output/train/20220512-160456-resnet50d-224/checkpoint-47.pth.tar

import csv

with open('/content/summary-adagrad.csv') as File:  
    Line_reader = csv.reader(File)

import matplotlib.pyplot as plt 
from matplotlib.pyplot import figure
import pandas as pd
import csv 

plt.rcParams["figure.figsize"] = [7.00, 5.00]
plt.rcParams["figure.autolayout"] = True

columns = ['train_loss', 'eval_loss']


df = pd.read_csv("/content/summary-adagrad.csv", usecols = columns)
  


df.columns=['Training Loss','Validation Loss']

df.plot()

plt.legend(loc='upper right')

plt.xlabel('Epochs') 

plt.ylabel('Loss Value') 

plt.title('Training and Validation Loss') 
plt.legend() 
plt.show()

import matplotlib.pyplot as plt 
from matplotlib.pyplot import figure
import pandas as pd
import csv 

plt.rcParams["figure.figsize"] = [7.00, 5.00]
plt.rcParams["figure.autolayout"] = True

columns = ['eval_top1', 'eval_top5']


df = pd.read_csv("/content/summary-adagrad.csv", usecols = columns)
  


df.columns=['Validation Top 1','Validation Top 5']

df.plot()

plt.legend(loc='lower right')

plt.xlabel('Epochs') 

plt.ylabel('Validation Value') 

plt.title('Top 1 & Top 5 Validation Accuracy') 
plt.legend() 
plt.show()